#!/usr/bin/env python3
"""Generate deterministic inventory for prohibited direct instantiations."""

import argparse
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_SCAN_PATHS = ("src",)
DEFAULT_OUTPUT = "docs/architecture/tmp_direct_instantiations.md"
INSTANTIATION_PATTERN = re.compile(
    r"^Direct instantiation of (?P<class_name>\w+) outside bootstrap: (?P<location>.+)$"
)

# Optional historical reference section. Keep empty when not needed.
RESOLVED_VIOLATIONS: tuple[tuple[str, str, str], ...] = ()


@dataclass(frozen=True)
class ViolationRow:
    """Parsed direct-instantiation violation row."""

    file_path: str
    class_name: str
    message: str
    line_number: int | None = None


def find_repo_root(anchor: str = "CLAUDE.md") -> Path:
    """Walk up from this file until a directory containing *anchor* is found."""
    current = Path(__file__).resolve().parent
    while current != current.parent:
        if (current / anchor).exists():
            return current
        current = current.parent
    raise RuntimeError(
        f"Repository root not found: no '{anchor}' file between "
        f"{Path(__file__).resolve()} and filesystem root."
    )


def parse_violation_message(message: str) -> ViolationRow | None:
    """Parse detector violation string into a structured row."""
    matched_message = INSTANTIATION_PATTERN.match(message.strip())
    if not matched_message:
        return None

    class_name = matched_message.group("class_name")
    location = matched_message.group("location").strip()
    file_path = location
    line_number: int | None = None

    # Optional support for future detector formats that include :<line> suffix.
    split_location = location.rsplit(":", maxsplit=1)
    if len(split_location) == 2 and split_location[1].isdigit():
        file_path = split_location[0]
        line_number = int(split_location[1])

    normalized_location = file_path if line_number is None else f"{file_path}:{line_number}"
    normalized_message = (
        f"Direct instantiation of {class_name} outside bootstrap: {normalized_location}"
    )

    return ViolationRow(
        file_path=file_path,
        class_name=class_name,
        line_number=line_number,
        message=normalized_message,
    )


def collect_violation_rows(raw_violations: list[str]) -> list[ViolationRow]:
    """Parse and deduplicate violation rows by class and file."""
    grouped_rows: dict[tuple[str, str], ViolationRow] = {}

    for raw_violation in raw_violations:
        parsed_violation = parse_violation_message(raw_violation)
        if parsed_violation is None:
            continue

        group_key = (parsed_violation.class_name, parsed_violation.file_path)
        existing_violation = grouped_rows.get(group_key)
        if existing_violation is None:
            grouped_rows[group_key] = parsed_violation
            continue

        if parsed_violation.line_number is not None:
            if existing_violation.line_number is None or parsed_violation.line_number < existing_violation.line_number:
                grouped_rows[group_key] = parsed_violation

    return sorted(
        grouped_rows.values(),
        key=lambda row: (row.class_name, row.file_path, row.line_number or 0),
    )


def run_check_architecture(repo_root: Path) -> str:
    """Run architecture checker and return combined output for verification section."""
    command = [
        sys.executable,
        "-m",
        "bpfw.cli",
        "check-architecture",
    ]
    completed = subprocess.run(
        command,
        cwd=str(repo_root),
        capture_output=True,
        text=True,
        check=False,
    )

    output_lines: list[str] = []
    stdout_text = completed.stdout.strip()
    stderr_text = completed.stderr.strip()

    if stdout_text:
        output_lines.append(stdout_text)
    if stderr_text:
        output_lines.append(stderr_text)

    if not output_lines:
        output_lines.append(f"(no output; exit code {completed.returncode})")

    return "\n".join(output_lines)


def render_markdown(violation_rows: list[ViolationRow], verification_output: str) -> str:
    """Render deterministic markdown inventory content."""
    timestamp = datetime.now(tz=timezone.utc).isoformat()
    total_violations = len(violation_rows)
    status_text = "sin pendientes" if total_violations == 0 else "pendientes de resolución"

    lines: list[str] = [
        "# Summary",
        "",
        "**Generated by:** `python tools/architecture/generate_instantiation_inventory.py`",
        f"**Date:** {timestamp}",
        f"**Total violations:** {total_violations} — {status_text}",
        "",
    ]

    if total_violations == 0:
        lines.append("All previously identified violations have been resolved.")
        lines.append("")
    else:
        lines.append("The following direct instantiation violations require attention:")
        lines.append("")

    lines.extend([
        "---",
        "",
        "# Current Violations",
        "",
        "| File | Concrete Class | Message |",
        "|---|---|---|",
    ])

    if violation_rows:
        for violation_row in violation_rows:
            lines.append(
                f"| `{violation_row.file_path}` | {violation_row.class_name} | {violation_row.message} |"
            )
    else:
        lines.append("| *(none)* | *(none)* | No direct instantiation violations detected. |")

    lines.append("")

    if RESOLVED_VIOLATIONS:
        lines.extend([
            "---",
            "",
            "# Resolved Findings (Historical Reference)",
            "",
            "| File | Concrete Class | Status |",
            "|---|---|---|",
        ])
        for file_path, class_name, status in RESOLVED_VIOLATIONS:
            lines.append(f"| `{file_path}` | {class_name} | {status} |")
        lines.append("")

    lines.extend([
        "---",
        "",
        "# Verification",
        "",
        "```",
        "$ python -m bpfw.cli check-architecture",
        verification_output,
        "```",
        "",
    ])

    return "\n".join(lines)


def write_text_atomic(output_path: Path, content: str) -> None:
    """Write file atomically via temp file + replace."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=output_path.parent,
            prefix=f".{output_path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary_file:
            temporary_file.write(content)
            temporary_file.flush()
            temporary_path = Path(temporary_file.name)

        if temporary_path is None:
            raise RuntimeError("Failed to create temporary file for atomic write.")

        temporary_path.replace(output_path)
    finally:
        if temporary_path is not None and temporary_path.exists():
            temporary_path.unlink(missing_ok=True)


def format_display_path(path: Path, repo_root: Path) -> str:
    """Return repo-relative path when possible, absolute otherwise."""
    try:
        return str(path.relative_to(repo_root))
    except ValueError:
        return str(path)


def parse_arguments() -> argparse.Namespace:
    """Build and parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description="Generate prohibited direct-instantiation inventory markdown.",
    )
    parser.add_argument(
        "--paths",
        nargs="+",
        default=None,
        help="Paths to scan. Defaults to src.",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=f"Output markdown path. Defaults to {DEFAULT_OUTPUT}.",
    )
    return parser.parse_args()


def main() -> int:
    """CLI entry point."""
    arguments = parse_arguments()

    try:
        repo_root = find_repo_root()

        if str(repo_root) not in sys.path:
            sys.path.insert(0, str(repo_root))

        from bpfw.architecture.checker import detect_direct_infra_instantiations

        path_arguments = arguments.paths if arguments.paths is not None else list(DEFAULT_SCAN_PATHS)
        scan_paths: list[Path] = []
        for path_argument in path_arguments:
            parsed_path = Path(path_argument)
            scan_paths.append(parsed_path if parsed_path.is_absolute() else repo_root / parsed_path)

        raw_violations = detect_direct_infra_instantiations(scan_paths)
        violation_rows = collect_violation_rows(raw_violations)
        verification_output = run_check_architecture(repo_root)
        markdown_content = render_markdown(violation_rows, verification_output)

        output_argument = Path(arguments.output)
        output_path = output_argument if output_argument.is_absolute() else repo_root / output_argument
        write_text_atomic(output_path, markdown_content)
        display_output_path = format_display_path(output_path, repo_root)

        print(f"Archivo creado/actualizado: {display_output_path}")
        print(
            f"Generated inventory: {display_output_path} "
            f"({len(violation_rows)} violations)",
            file=sys.stderr,
        )
        return 0
    except RuntimeError as runtime_error:
        print(str(runtime_error), file=sys.stderr)
        return 1
    except Exception as unexpected_error:
        print(f"Error generating inventory: {unexpected_error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
